---
apiVersion: v1
metadata:
  name: helloword-configmap
data:
  helloworld: |-
    Hello world
kind: ConfigMap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: helloword-configmap-vol
      volumes:
        - name: helloword-configmap-vol
          configMap:
            name: helloword-configmap
            items:
              - key: helloworld
                path:  index.html

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
   - port: 80
     nodePort: 31514

