- name: Include common playbook
  import_playbook: common.yml

- name: Include kubernetes playbook
  import_playbook: kubernetes.yml

- name: Include nginx deployment playbook
  import_playbook: nginx-deployment.yml

- name: Include tomcat deployment playbook
  import_playbook: tomcat-deployment.yml

- name: Include jenkins deployment playbook
  import_playbook: jenkins-deployment.yml

- name: Include test
  import_playbook: test.yml