- hosts: all
  become: True
  tasks:
    - name: Wait nginx
      wait_for:
        port: 31514
        delay: 5

    - name: Wait tomcat
      wait_for:
        port: 31515
        delay: 5

    - name: Create nginx.yml
      command: curl localhost:31514
      register: test_nginx

    - debug:
        var: test_nginx.stdout_lines

    - name: Create tomcat.yml
      command: curl localhost:31515/sample/
      register: test_tomcat

    - debug:
        var: test_tomcat.stdout_lines